In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
%matplotlib inline

In [2]:
from  sklearn.datasets import  load_iris
iris = load_iris()
list(iris.keys())

['data',
 'target',
 'frame',
 'target_names',
 'DESCR',
 'feature_names',
 'filename',
 'data_module']

In [3]:
X = iris.data[:,:2]
y = iris.target

In [4]:
random.seed(64)
sample_size = random.sample( range(0,149),5)

X_train = X[sample_size]
y_train = y[sample_size]

In [ ]:
def initialize_parameters():
    weights = [] 
    bias = []
    bias.append(random.random(3,1))
    weights.append(random.random(3,2))
    
    return weights, bias

In [ ]:
def model(X, y, iterations):
    
    costs = []

    counter = 0
    n = len(X)
    w, b = initialize_parameters()
   
    while iterations > counter:
        
        z = np.dot(w.T, X.T) + b
        pred = 1 / (1 + np.exp(-z))
        
        #Calculate Loss Function
        entropy = -(1/n) * np.sum(y*np.log(pred)+(1-y)*np.log(1-pred))
        
        # find gradient (back propagation)
        dw = 1/n * np.dot(X.T, (pred - y).T)
        db = 1/n* np.sum(pred - y)
        
        w = w - 0.05 * dw
        b = b - 0.05 * db

In [ ]:
weights, bias = initialize_parameters(X_train)

In [ ]:
weights

In [ ]:
np.sum(X_train * np.random.rand(5,2))

In [ ]:
X_train

In [14]:
np.random.rand(3,2)

array([[0.71075037, 0.22890993],
       [0.88688261, 0.32913875],
       [0.41373835, 0.90385746]])

In [5]:
w_temp = np.random.rand(3,2)
b_temp = np.random.rand(3,1)
input_layer = []
pred_input = []

for n_weights, n_bias in zip(w_temp,b_temp):
    layer1_out = 0
    
    for n_inputs, weight in zip(X_train.T, n_weights):
        layer1_out  += n_inputs * weight
        
    layer1_out  += n_bias
    z = 1 / (1 + np.exp(-layer1_out))
    
    pred_input.append(z)
    input_layer.append(layer1_out)

In [6]:
input_layer

[array([8.26511831, 8.62044413, 8.96253203, 9.22601778, 8.44879846]),
 array([4.84370348, 4.70849168, 5.33875642, 5.41131951, 4.42815369]),
 array([2.35579521, 2.41190469, 2.53595378, 2.5934767 , 2.3529683 ])]

In [7]:
pred_input

[array([0.99974273, 0.99981965, 0.99987189, 0.99990157, 0.99978589]),
 array([0.99218375, 0.99106223, 0.99522111, 0.99555411, 0.98820429]),
 array([0.91339376, 0.9177306 , 0.92662419, 0.93044057, 0.91316988])]

In [12]:
w_temp2 = np.random.rand(3,3)
b_temp2 = np.random.rand(3,1)
hidden_layer = []
pred_hidden = []
for h_weights, h_bias in zip(w_temp2,b_temp2):
    hidden_out = 0
    
    for h_inputs, h_weight in zip(input_layer, h_weights):
        hidden_out += h_inputs * h_weight
        
    hidden_out += h_bias    
    softmax = np.exp(hidden_out) / hidden_out.sum() 

    pred_hidden.append(softmax)
    hidden_layer.append(hidden_out)

In [13]:
hidden_layer

[array([8.57015942, 8.58621976, 9.34991642, 9.53187902, 8.2383549 ]),
 array([1.00809951, 1.01401632, 1.09371372, 1.11491965, 0.97752128]),
 array([ 9.32991743,  9.67851102, 10.09606897, 10.37318789,  9.47286679])]

In [ ]:
r = hidden_layer[0]

In [ ]:
np.exp(r)

In [ ]:
X_train.T[1]

In [ ]:
w_temp[0][0]

In [ ]:
w_temp[0][1]

In [ ]:
z = []
pred = []
for j in range(0,3):
    for i in range(0,5):
        X2 = (X_train.T[1] * w_temp[j][1]) 
        X1 = (X_train.T[0] * w_temp[j][0])
        z.append((X1[i] + X2[i]) + b_temp[j])
        pred.append(1 / (1 + np.exp(-z[i])))

In [ ]:
pred

In [ ]:
pred11

In [ ]:
N1 = np.array(pred[0:5]).T
N2 = np.array(pred[5:10]).T
N3 = np.array(pred[10:15]).T

In [ ]:
w_temp2 = np.random.rand(3,3)
b_temp2 = np.random.rand(3,1)
z1 = []
final_pred = []

for j in range(0,3):
    new_n1 = N1[0] * w_temp2[j][0]
    new_n2 = N2[0] * w_temp2[j][1]
    new_n3 = N3[0] * w_temp2[j][2]
    for i in range(0,5):
        z1.append((new_n1[i] + new_n2[i] + new_n3[i]) + b_temp2[j])
        

In [ ]:
e1 = np.array(z1[0:5]).T
e2 = np.array(z1[5:10]).T
e3 = np.array(z1[10:15]).T

In [ ]:
np.exp(e1) / e1.sum()

In [ ]:
np.exp(e2) / e2.sum()

In [ ]:
np.exp(e3) / e3.sum()

In [ ]:
e3

In [ ]:
pred_hidden

In [ ]:
b_temp2

In [ ]:
z1 = []



In [ ]:
new_n1 = z1[0:15]

In [ ]:
new_n2 = z1[15:30]

In [ ]:
new_n3 = z1[30:45]

In [ ]:
def softmax(vector):
    e = np.exp(vector)
    return e / e.sum()

In [ ]:
pred_n1 = []
for i in range(0,len(new_n1)):
    pred_n1.append(np.exp(new_n1[i]) / np.array(new_n1).sum())


In [ ]:
pred_n1

In [ ]:
w_temp2[0][0]

In [ ]:
w_temp11

In [ ]:
N1[0] * w_temp2[0][0]

In [ ]:
N2[0] * w_temp2[0][1]

In [ ]:
N3[0] * w_temp2[0][2]

In [ ]:
N1[0] * w_temp2[1][0]

In [ ]:
N2[0] * w_temp2[1][1]

In [ ]:
N3[0] * w_temp2[1][2]

In [ ]:
N1[0] * w_temp2[2][0]

In [ ]:
N2[0] * w_temp2[2][1]

In [ ]:
N3[0] * w_temp2[2][2]