In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
%matplotlib inline

In [2]:
from  sklearn.datasets import  load_iris
iris = load_iris()
list(iris.keys())

['data',
 'target',
 'frame',
 'target_names',
 'DESCR',
 'feature_names',
 'filename',
 'data_module']

In [3]:
X = iris.data[:,:2]
y = iris.target

In [4]:
random.seed(64)
sample_size = random.sample( range(0,149),5)

X_train = X[sample_size]
y_train = y[sample_size]

In [5]:
random.seed(64)
sample_size = random.sample( range(0,149),5)

X_train = X[sample_size]
y_train = y[sample_size]

In [24]:
def initialize_parameters(n, neurons):
    bias = (np.random.rand(neurons,1))
    weights = (np.random.rand(neurons,n))
    
    return weights, bias

In [25]:
def layer1(X, neurons):
    
    input_layer = []
    pred_input = []
    
    n = X.shape[1]
    weights, bias = initialize_parameters(n, neurons)
    
    layer1_out =  np.dot(weights, X.T) + bias
    z = 1 / (1 + np.exp(-layer1_out))

    pred_input.append(z)
    input_layer.append(layer1_out)
    
    return pred_input[0], input_layer[0]

In [26]:
pred_input, input_layer = layer1(X_train, 3)

In [27]:
input_layer

array([[8.17458451, 8.51957282, 8.86371525, 9.12226424, 8.34746315],
       [4.26175926, 4.69878351, 4.56809197, 4.76683384, 4.73832401],
       [2.19410317, 2.17893407, 2.41699127, 2.46316588, 2.07141575]])

In [28]:
def layer2(input_layer, neurons):
    
    hidden_layer = []
    pred_hidden = []
    
    n = np.array(input_layer).shape[0]
    weights, bias = initialize_parameters(n, neurons)
    
    hidden_out = np.dot(weights, input_layer) + bias
    softmax = np.exp(hidden_out) / np.exp(hidden_out).sum() 
    
    pred_hidden.append(softmax)
    hidden_layer.append(hidden_out)
    
    return hidden_layer[0], pred_hidden

In [33]:
hidden_layer, pred_hidden = layer2(input_layer, neurons= 3)

In [34]:
hidden_layer

array([[ 2.89568737,  3.07411934,  3.05860031,  3.14834452,  3.0730629 ],
       [11.65794258, 12.29310134, 12.52720995, 12.91243126, 12.15781748],
       [ 8.43821205,  8.78633752,  9.06157032,  9.3060979 ,  8.64540781]])

In [35]:
hidden_layer2, pred_hidden2 = layer2(hidden_layer, neurons= 5)

In [36]:
hidden_layer2

array([[ 9.20245595,  9.653829  ,  9.78429112, 10.04988661,  9.57401109],
       [11.74704477, 12.36067447, 12.57962057, 12.95014202, 12.23326125],
       [ 4.77655491,  4.98175039,  5.12300338,  5.2623676 ,  4.90821742],
       [19.33947418, 20.2631388 , 20.69030525, 21.27021323, 20.02698747],
       [ 5.50245742,  5.76067298,  5.89394537,  6.05921086,  5.68835755]])