In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random

In [2]:
from  sklearn.datasets import  load_iris
iris = load_iris()
list(iris.keys())

['data',
 'target',
 'frame',
 'target_names',
 'DESCR',
 'feature_names',
 'filename',
 'data_module']

In [3]:

X = iris.data[:,:2]
y = iris.target

In [4]:
random.seed(64)
sample_size = random.sample( range(0,149),5)

X_train = X[sample_size]
y_train = y[sample_size]

In [5]:
def initialize_parameters(n):
    bias = (np.random.rand(3,1))
    weights = (np.random.rand(3,n))
    
    return weights, bias

In [6]:
def layer1(X):
    
    input_layer = []
    pred_input = []
    
    n = X.shape[1]
    weights, bias = initialize_parameters(n)

    for n_weights, n_bias in zip(weights, bias):
        layer1_out = 0

        for n_inputs, weight in zip(X.T, n_weights):
            layer1_out  += n_inputs * weight

        layer1_out  += n_bias
        z = 1 / (1 + np.exp(-layer1_out))

        pred_input.append(z)
        input_layer.append(layer1_out)
    
    return pred_input, input_layer

pred_input, input_layer = layer1(X_train)

In [12]:
input_layer

[array([3.37051059, 3.62612403, 3.56630839, 3.68633004, 3.64169417]),
 array([6.74431967, 6.72907457, 7.4002438 , 7.54481324, 6.42469061]),
 array([6.69225835, 6.69926041, 7.33748331, 7.48619414, 6.40884082])]

In [9]:
def layer2(input_layer):
    
    hidden_layer = []
    pred_hidden = []
    
    n = np.array(input_layer).shape[0]
    weights, bias = initialize_parameters(n)
    
    for h_weights, h_bias in zip(weights, bias):
        hidden_out = 0

        for n_inputs1, h_weight in zip(input_layer, h_weights):
            hidden_out += n_inputs1 * h_weight

        hidden_out += h_bias    
        #softmax = np.exp(hidden_out) / hidden_out.sum() 

        #pred_hidden.append(softmax)
        hidden_layer.append(hidden_out)
    
    return hidden_layer, pred_hidden
hidden_layer, pred_hidden = layer2(input_layer)

In [10]:
hidden_layer

[array([5.55863794, 5.58291612, 6.0602371 , 6.18141   , 5.36484849]),
 array([ 9.15507563,  9.36962551,  9.85139386, 10.07303774,  9.14088763]),
 array([ 9.11216384,  9.2394323 ,  9.8664022 , 10.07542205,  8.94866105])]